### PR TITLE
Add auto-update feature, refactor code and fix bugs

### PR DESCRIPTION
**Pull request by xilopaint**
**New**
• Add auto-update feature using OneUpdater by @vitorgalvao.

**Fixes**
• Fix a bug in the battery health calculation.
• Fix a bug in the battery temperature calculation.

**Improvements**
• Refactor code and repository.

### CODE REVIEW

**Comment by xilopaint** [comment]
In order to make the auto-update feature work in the future you have to make a release with the tag `v1.0`.

**Comment by yock** [comment]
As someone who uses this workflow it excites me to see this PR. I took the liberty of cloning the forked repo and testing the workflow. It works well and the removal of the intermediate text file makes this noticeably faster, I think. I'd love to see this get merged.

**Comment by BenziAhamed** [comment]
Closes #8

**Comment by BenziAhamed** [comment]
Many thanks for this @xilopaint!

**Pull request merged**
